// Public Browse API gRPC contract.
// Read-only browsing and search for published ontologies.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: public_browse/v1/public_browse.proto

package publicbrowsev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "vedo-core/src/services/shared/proto/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest_SearchScope int32

const (
	SearchRequest_SEARCH_SCOPE_UNSPECIFIED SearchRequest_SearchScope = 0
	SearchRequest_SEARCH_SCOPE_CLASS       SearchRequest_SearchScope = 1
	SearchRequest_SEARCH_SCOPE_PROPERTY    SearchRequest_SearchScope = 2
	SearchRequest_SEARCH_SCOPE_ONTOLOGY    SearchRequest_SearchScope = 3
)

// Enum value maps for SearchRequest_SearchScope.
var (
	SearchRequest_SearchScope_name = map[int32]string{
		0: "SEARCH_SCOPE_UNSPECIFIED",
		1: "SEARCH_SCOPE_CLASS",
		2: "SEARCH_SCOPE_PROPERTY",
		3: "SEARCH_SCOPE_ONTOLOGY",
	}
	SearchRequest_SearchScope_value = map[string]int32{
		"SEARCH_SCOPE_UNSPECIFIED": 0,
		"SEARCH_SCOPE_CLASS":       1,
		"SEARCH_SCOPE_PROPERTY":    2,
		"SEARCH_SCOPE_ONTOLOGY":    3,
	}
)

func (x SearchRequest_SearchScope) Enum() *SearchRequest_SearchScope {
	p := new(SearchRequest_SearchScope)
	*p = x
	return p
}

func (x SearchRequest_SearchScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SearchRequest_SearchScope) Descriptor() protoreflect.EnumDescriptor {
	return file_public_browse_v1_public_browse_proto_enumTypes[0].Descriptor()
}

func (SearchRequest_SearchScope) Type() protoreflect.EnumType {
	return &file_public_browse_v1_public_browse_proto_enumTypes[0]
}

func (x SearchRequest_SearchScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SearchRequest_SearchScope.Descriptor instead.
func (SearchRequest_SearchScope) EnumDescriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{2, 0}
}

type BrowseOntologyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	VersionTag    string                 `protobuf:"bytes,2,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"` // empty = latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseOntologyRequest) Reset() {
	*x = BrowseOntologyRequest{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseOntologyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseOntologyRequest) ProtoMessage() {}

func (x *BrowseOntologyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseOntologyRequest.ProtoReflect.Descriptor instead.
func (*BrowseOntologyRequest) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{0}
}

func (x *BrowseOntologyRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *BrowseOntologyRequest) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

type BrowseOntologyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VersionTag    string                 `protobuf:"bytes,4,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"`
	ClassCount    int32                  `protobuf:"varint,5,opt,name=class_count,json=classCount,proto3" json:"class_count,omitempty"`
	PropertyCount int32                  `protobuf:"varint,6,opt,name=property_count,json=propertyCount,proto3" json:"property_count,omitempty"`
	RootClasses   []string               `protobuf:"bytes,7,rep,name=root_classes,json=rootClasses,proto3" json:"root_classes,omitempty"` // root class IRIs
	OntologyTtl   string                 `protobuf:"bytes,8,opt,name=ontology_ttl,json=ontologyTtl,proto3" json:"ontology_ttl,omitempty"` // Turtle serialization
	Error         *v1.ErrorDetail        `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BrowseOntologyResponse) Reset() {
	*x = BrowseOntologyResponse{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BrowseOntologyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BrowseOntologyResponse) ProtoMessage() {}

func (x *BrowseOntologyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BrowseOntologyResponse.ProtoReflect.Descriptor instead.
func (*BrowseOntologyResponse) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{1}
}

func (x *BrowseOntologyResponse) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *BrowseOntologyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BrowseOntologyResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *BrowseOntologyResponse) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *BrowseOntologyResponse) GetClassCount() int32 {
	if x != nil {
		return x.ClassCount
	}
	return 0
}

func (x *BrowseOntologyResponse) GetPropertyCount() int32 {
	if x != nil {
		return x.PropertyCount
	}
	return 0
}

func (x *BrowseOntologyResponse) GetRootClasses() []string {
	if x != nil {
		return x.RootClasses
	}
	return nil
}

func (x *BrowseOntologyResponse) GetOntologyTtl() string {
	if x != nil {
		return x.OntologyTtl
	}
	return ""
}

func (x *BrowseOntologyResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Query         string                    `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Scope         SearchRequest_SearchScope `protobuf:"varint,2,opt,name=scope,proto3,enum=vedo.public_browse.v1.SearchRequest_SearchScope" json:"scope,omitempty"`
	Pagination    *v1.PaginationRequest     `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetScope() SearchRequest_SearchScope {
	if x != nil {
		return x.Scope
	}
	return SearchRequest_SEARCH_SCOPE_UNSPECIFIED
}

func (x *SearchRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntityId      string                 `protobuf:"bytes,1,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	OntologyId    string                 `protobuf:"bytes,4,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	OntologyName  string                 `protobuf:"bytes,5,opt,name=ontology_name,json=ontologyName,proto3" json:"ontology_name,omitempty"`
	EntityType    string                 `protobuf:"bytes,6,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	Score         float32                `protobuf:"fixed32,7,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{3}
}

func (x *SearchResult) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *SearchResult) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SearchResult) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SearchResult) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *SearchResult) GetOntologyName() string {
	if x != nil {
		return x.OntologyName
	}
	return ""
}

func (x *SearchResult) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *SearchResult) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *SearchResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetClassHierarchyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	VersionTag    string                 `protobuf:"bytes,2,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"`
	ClassId       string                 `protobuf:"bytes,3,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"` // empty = return full hierarchy from root
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassHierarchyRequest) Reset() {
	*x = GetClassHierarchyRequest{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassHierarchyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassHierarchyRequest) ProtoMessage() {}

func (x *GetClassHierarchyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassHierarchyRequest.ProtoReflect.Descriptor instead.
func (*GetClassHierarchyRequest) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{5}
}

func (x *GetClassHierarchyRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *GetClassHierarchyRequest) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *GetClassHierarchyRequest) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

type HierarchyNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClassId       string                 `protobuf:"bytes,1,opt,name=class_id,json=classId,proto3" json:"class_id,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	ChildCount    int32                  `protobuf:"varint,3,opt,name=child_count,json=childCount,proto3" json:"child_count,omitempty"`
	Children      []*HierarchyNode       `protobuf:"bytes,4,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HierarchyNode) Reset() {
	*x = HierarchyNode{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HierarchyNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HierarchyNode) ProtoMessage() {}

func (x *HierarchyNode) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HierarchyNode.ProtoReflect.Descriptor instead.
func (*HierarchyNode) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{6}
}

func (x *HierarchyNode) GetClassId() string {
	if x != nil {
		return x.ClassId
	}
	return ""
}

func (x *HierarchyNode) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *HierarchyNode) GetChildCount() int32 {
	if x != nil {
		return x.ChildCount
	}
	return 0
}

func (x *HierarchyNode) GetChildren() []*HierarchyNode {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetClassHierarchyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          []*HierarchyNode       `protobuf:"bytes,1,rep,name=tree,proto3" json:"tree,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassHierarchyResponse) Reset() {
	*x = GetClassHierarchyResponse{}
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassHierarchyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassHierarchyResponse) ProtoMessage() {}

func (x *GetClassHierarchyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_public_browse_v1_public_browse_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassHierarchyResponse.ProtoReflect.Descriptor instead.
func (*GetClassHierarchyResponse) Descriptor() ([]byte, []int) {
	return file_public_browse_v1_public_browse_proto_rawDescGZIP(), []int{7}
}

func (x *GetClassHierarchyResponse) GetTree() []*HierarchyNode {
	if x != nil {
		return x.Tree
	}
	return nil
}

func (x *GetClassHierarchyResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_public_browse_v1_public_browse_proto protoreflect.FileDescriptor

const file_public_browse_v1_public_browse_proto_rawDesc = "" +
	"\n" +
	"$public_browse/v1/public_browse.proto\x12\x15vedo.public_browse.v1\x1a\x16common/v1/common.proto\"Y\n" +
	"\x15BrowseOntologyRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1f\n" +
	"\vversion_tag\x18\x02 \x01(\tR\n" +
	"versionTag\"\xd1\x02\n" +
	"\x16BrowseOntologyResponse\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vversion_tag\x18\x04 \x01(\tR\n" +
	"versionTag\x12\x1f\n" +
	"\vclass_count\x18\x05 \x01(\x05R\n" +
	"classCount\x12%\n" +
	"\x0eproperty_count\x18\x06 \x01(\x05R\rpropertyCount\x12!\n" +
	"\froot_classes\x18\a \x03(\tR\vrootClasses\x12!\n" +
	"\fontology_ttl\x18\b \x01(\tR\vontologyTtl\x121\n" +
	"\x05error\x18\t \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"\xab\x02\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12F\n" +
	"\x05scope\x18\x02 \x01(\x0e20.vedo.public_browse.v1.SearchRequest.SearchScopeR\x05scope\x12A\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2!.vedo.common.v1.PaginationRequestR\n" +
	"pagination\"y\n" +
	"\vSearchScope\x12\x1c\n" +
	"\x18SEARCH_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SEARCH_SCOPE_CLASS\x10\x01\x12\x19\n" +
	"\x15SEARCH_SCOPE_PROPERTY\x10\x02\x12\x19\n" +
	"\x15SEARCH_SCOPE_ONTOLOGY\x10\x03\"\xe0\x01\n" +
	"\fSearchResult\x12\x1b\n" +
	"\tentity_id\x18\x01 \x01(\tR\bentityId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vontology_id\x18\x04 \x01(\tR\n" +
	"ontologyId\x12#\n" +
	"\rontology_name\x18\x05 \x01(\tR\fontologyName\x12\x1f\n" +
	"\ventity_type\x18\x06 \x01(\tR\n" +
	"entityType\x12\x14\n" +
	"\x05score\x18\a \x01(\x02R\x05score\"\xc6\x01\n" +
	"\x0eSearchResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.vedo.public_browse.v1.SearchResultR\aresults\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".vedo.common.v1.PaginationResponseR\n" +
	"pagination\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"w\n" +
	"\x18GetClassHierarchyRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1f\n" +
	"\vversion_tag\x18\x02 \x01(\tR\n" +
	"versionTag\x12\x19\n" +
	"\bclass_id\x18\x03 \x01(\tR\aclassId\"\xa3\x01\n" +
	"\rHierarchyNode\x12\x19\n" +
	"\bclass_id\x18\x01 \x01(\tR\aclassId\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1f\n" +
	"\vchild_count\x18\x03 \x01(\x05R\n" +
	"childCount\x12@\n" +
	"\bchildren\x18\x04 \x03(\v2$.vedo.public_browse.v1.HierarchyNodeR\bchildren\"\x88\x01\n" +
	"\x19GetClassHierarchyResponse\x128\n" +
	"\x04tree\x18\x01 \x03(\v2$.vedo.public_browse.v1.HierarchyNodeR\x04tree\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error2\xd3\x02\n" +
	"\x13PublicBrowseService\x12m\n" +
	"\x0eBrowseOntology\x12,.vedo.public_browse.v1.BrowseOntologyRequest\x1a-.vedo.public_browse.v1.BrowseOntologyResponse\x12U\n" +
	"\x06Search\x12$.vedo.public_browse.v1.SearchRequest\x1a%.vedo.public_browse.v1.SearchResponse\x12v\n" +
	"\x11GetClassHierarchy\x12/.vedo.public_browse.v1.GetClassHierarchyRequest\x1a0.vedo.public_browse.v1.GetClassHierarchyResponseBb\n" +
	"\x19com.vedo.public_browse.v1P\x01ZCvedo-core/src/services/shared/proto/public_browse/v1;publicbrowsev1b\x06proto3"

var (
	file_public_browse_v1_public_browse_proto_rawDescOnce sync.Once
	file_public_browse_v1_public_browse_proto_rawDescData []byte
)

func file_public_browse_v1_public_browse_proto_rawDescGZIP() []byte {
	file_public_browse_v1_public_browse_proto_rawDescOnce.Do(func() {
		file_public_browse_v1_public_browse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_public_browse_v1_public_browse_proto_rawDesc), len(file_public_browse_v1_public_browse_proto_rawDesc)))
	})
	return file_public_browse_v1_public_browse_proto_rawDescData
}

var file_public_browse_v1_public_browse_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_public_browse_v1_public_browse_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_public_browse_v1_public_browse_proto_goTypes = []any{
	(SearchRequest_SearchScope)(0),    // 0: vedo.public_browse.v1.SearchRequest.SearchScope
	(*BrowseOntologyRequest)(nil),     // 1: vedo.public_browse.v1.BrowseOntologyRequest
	(*BrowseOntologyResponse)(nil),    // 2: vedo.public_browse.v1.BrowseOntologyResponse
	(*SearchRequest)(nil),             // 3: vedo.public_browse.v1.SearchRequest
	(*SearchResult)(nil),              // 4: vedo.public_browse.v1.SearchResult
	(*SearchResponse)(nil),            // 5: vedo.public_browse.v1.SearchResponse
	(*GetClassHierarchyRequest)(nil),  // 6: vedo.public_browse.v1.GetClassHierarchyRequest
	(*HierarchyNode)(nil),             // 7: vedo.public_browse.v1.HierarchyNode
	(*GetClassHierarchyResponse)(nil), // 8: vedo.public_browse.v1.GetClassHierarchyResponse
	(*v1.ErrorDetail)(nil),            // 9: vedo.common.v1.ErrorDetail
	(*v1.PaginationRequest)(nil),      // 10: vedo.common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),     // 11: vedo.common.v1.PaginationResponse
}
var file_public_browse_v1_public_browse_proto_depIdxs = []int32{
	9,  // 0: vedo.public_browse.v1.BrowseOntologyResponse.error:type_name -> vedo.common.v1.ErrorDetail
	0,  // 1: vedo.public_browse.v1.SearchRequest.scope:type_name -> vedo.public_browse.v1.SearchRequest.SearchScope
	10, // 2: vedo.public_browse.v1.SearchRequest.pagination:type_name -> vedo.common.v1.PaginationRequest
	4,  // 3: vedo.public_browse.v1.SearchResponse.results:type_name -> vedo.public_browse.v1.SearchResult
	11, // 4: vedo.public_browse.v1.SearchResponse.pagination:type_name -> vedo.common.v1.PaginationResponse
	9,  // 5: vedo.public_browse.v1.SearchResponse.error:type_name -> vedo.common.v1.ErrorDetail
	7,  // 6: vedo.public_browse.v1.HierarchyNode.children:type_name -> vedo.public_browse.v1.HierarchyNode
	7,  // 7: vedo.public_browse.v1.GetClassHierarchyResponse.tree:type_name -> vedo.public_browse.v1.HierarchyNode
	9,  // 8: vedo.public_browse.v1.GetClassHierarchyResponse.error:type_name -> vedo.common.v1.ErrorDetail
	1,  // 9: vedo.public_browse.v1.PublicBrowseService.BrowseOntology:input_type -> vedo.public_browse.v1.BrowseOntologyRequest
	3,  // 10: vedo.public_browse.v1.PublicBrowseService.Search:input_type -> vedo.public_browse.v1.SearchRequest
	6,  // 11: vedo.public_browse.v1.PublicBrowseService.GetClassHierarchy:input_type -> vedo.public_browse.v1.GetClassHierarchyRequest
	2,  // 12: vedo.public_browse.v1.PublicBrowseService.BrowseOntology:output_type -> vedo.public_browse.v1.BrowseOntologyResponse
	5,  // 13: vedo.public_browse.v1.PublicBrowseService.Search:output_type -> vedo.public_browse.v1.SearchResponse
	8,  // 14: vedo.public_browse.v1.PublicBrowseService.GetClassHierarchy:output_type -> vedo.public_browse.v1.GetClassHierarchyResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_public_browse_v1_public_browse_proto_init() }
func file_public_browse_v1_public_browse_proto_init() {
	if File_public_browse_v1_public_browse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_public_browse_v1_public_browse_proto_rawDesc), len(file_public_browse_v1_public_browse_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_public_browse_v1_public_browse_proto_goTypes,
		DependencyIndexes: file_public_browse_v1_public_browse_proto_depIdxs,
		EnumInfos:         file_public_browse_v1_public_browse_proto_enumTypes,
		MessageInfos:      file_public_browse_v1_public_browse_proto_msgTypes,
	}.Build()
	File_public_browse_v1_public_browse_proto = out.File
	file_public_browse_v1_public_browse_proto_goTypes = nil
	file_public_browse_v1_public_browse_proto_depIdxs = nil
}
