// Public Browse API gRPC contract.
// Read-only browsing and search for published ontologies.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: public_browse/v1/public_browse.proto

package publicbrowsev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublicBrowseService_BrowseOntology_FullMethodName    = "/vedo.public_browse.v1.PublicBrowseService/BrowseOntology"
	PublicBrowseService_Search_FullMethodName            = "/vedo.public_browse.v1.PublicBrowseService/Search"
	PublicBrowseService_GetClassHierarchy_FullMethodName = "/vedo.public_browse.v1.PublicBrowseService/GetClassHierarchy"
)

// PublicBrowseServiceClient is the client API for PublicBrowseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublicBrowseServiceClient interface {
	BrowseOntology(ctx context.Context, in *BrowseOntologyRequest, opts ...grpc.CallOption) (*BrowseOntologyResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	GetClassHierarchy(ctx context.Context, in *GetClassHierarchyRequest, opts ...grpc.CallOption) (*GetClassHierarchyResponse, error)
}

type publicBrowseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublicBrowseServiceClient(cc grpc.ClientConnInterface) PublicBrowseServiceClient {
	return &publicBrowseServiceClient{cc}
}

func (c *publicBrowseServiceClient) BrowseOntology(ctx context.Context, in *BrowseOntologyRequest, opts ...grpc.CallOption) (*BrowseOntologyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseOntologyResponse)
	err := c.cc.Invoke(ctx, PublicBrowseService_BrowseOntology_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicBrowseServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, PublicBrowseService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publicBrowseServiceClient) GetClassHierarchy(ctx context.Context, in *GetClassHierarchyRequest, opts ...grpc.CallOption) (*GetClassHierarchyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClassHierarchyResponse)
	err := c.cc.Invoke(ctx, PublicBrowseService_GetClassHierarchy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublicBrowseServiceServer is the server API for PublicBrowseService service.
// All implementations must embed UnimplementedPublicBrowseServiceServer
// for forward compatibility.
type PublicBrowseServiceServer interface {
	BrowseOntology(context.Context, *BrowseOntologyRequest) (*BrowseOntologyResponse, error)
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	GetClassHierarchy(context.Context, *GetClassHierarchyRequest) (*GetClassHierarchyResponse, error)
	mustEmbedUnimplementedPublicBrowseServiceServer()
}

// UnimplementedPublicBrowseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublicBrowseServiceServer struct{}

func (UnimplementedPublicBrowseServiceServer) BrowseOntology(context.Context, *BrowseOntologyRequest) (*BrowseOntologyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BrowseOntology not implemented")
}
func (UnimplementedPublicBrowseServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedPublicBrowseServiceServer) GetClassHierarchy(context.Context, *GetClassHierarchyRequest) (*GetClassHierarchyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClassHierarchy not implemented")
}
func (UnimplementedPublicBrowseServiceServer) mustEmbedUnimplementedPublicBrowseServiceServer() {}
func (UnimplementedPublicBrowseServiceServer) testEmbeddedByValue()                             {}

// UnsafePublicBrowseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublicBrowseServiceServer will
// result in compilation errors.
type UnsafePublicBrowseServiceServer interface {
	mustEmbedUnimplementedPublicBrowseServiceServer()
}

func RegisterPublicBrowseServiceServer(s grpc.ServiceRegistrar, srv PublicBrowseServiceServer) {
	// If the following call panics, it indicates UnimplementedPublicBrowseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublicBrowseService_ServiceDesc, srv)
}

func _PublicBrowseService_BrowseOntology_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseOntologyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicBrowseServiceServer).BrowseOntology(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicBrowseService_BrowseOntology_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicBrowseServiceServer).BrowseOntology(ctx, req.(*BrowseOntologyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicBrowseService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicBrowseServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicBrowseService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicBrowseServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublicBrowseService_GetClassHierarchy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassHierarchyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublicBrowseServiceServer).GetClassHierarchy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublicBrowseService_GetClassHierarchy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublicBrowseServiceServer).GetClassHierarchy(ctx, req.(*GetClassHierarchyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublicBrowseService_ServiceDesc is the grpc.ServiceDesc for PublicBrowseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublicBrowseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vedo.public_browse.v1.PublicBrowseService",
	HandlerType: (*PublicBrowseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BrowseOntology",
			Handler:    _PublicBrowseService_BrowseOntology_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _PublicBrowseService_Search_Handler,
		},
		{
			MethodName: "GetClassHierarchy",
			Handler:    _PublicBrowseService_GetClassHierarchy_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public_browse/v1/public_browse.proto",
}
