// @ctx: Global setup for Playwright API tests.
//
// Auto-regenerates JWT tokens before test run when existing tokens are
// expired or near expiry. This prevents the "expired token" regression
// where hardcoded JWT timestamps fall behind the current date.
//
// The tokens are signed with test-jwt-key.pem (RS256) and verified by the
// API gateway via JWT_DEV_PUBLIC_KEY_PEM in deploy/docker-compose.test.yml.
import { readFileSync, writeFileSync, existsSync } from 'fs';
import { resolve } from 'path';

// jsonwebtoken is an ESM-compatible CJS package; use dynamic import or require.
const jwt = require('jsonwebtoken');

const KEY_PATH = resolve(__dirname, 'test-jwt-key.pem');
const OUTPUT_PATH = resolve(__dirname, 'tests', 'jwt-tokens.ts');

/**
 * Decode the base64 payload of a JWT without verifying the signature.
 */
function decodePayload(token: string): Record<string, unknown> | null {
  try {
    const parts = token.split('.');
    if (parts.length !== 3) return null;
    const raw = Buffer.from(parts[1], 'base64url').toString('utf8');
    return JSON.parse(raw) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Check whether the existing jwt-tokens.ts contains tokens that are still
 * valid. Returns true when the OWNER_JWT token has an `exp` at least 1 hour
 * in the future, avoiding unnecessary file churn on every test run.
 */
function areTokensStillValid(): boolean {
  try {
    if (!existsSync(OUTPUT_PATH)) return false;
    const content = readFileSync(OUTPUT_PATH, 'utf8');
    const match = content.match(/OWNER_JWT\s*=\s*'([^']+)'/);
    if (!match) return false;
    const payload = decodePayload(match[1]);
    if (!payload || typeof payload.exp !== 'number') return false;
    const remainingMs = payload.exp * 1000 - Date.now();
    // Consider valid if more than 1 hour until expiry
    return remainingMs > 3600_000;
  } catch {
    return false;
  }
}

/**
 * Global setup function — called once by Playwright before all tests.
 *
 * Regenerates JWT tokens only when:
 * 1. The `test-jwt-key.pem` file exists
 * 2. Existing tokens are expired or within 1 hour of expiry
 */
function setup(): void {
  if (!existsSync(KEY_PATH)) {
    console.warn(
      '[setup] WARNING: test-jwt-key.pem not found at',
      KEY_PATH,
      '— JWT tokens will NOT be regenerated. Tests may fail with 401 if tokens expire.',
    );
    return;
  }

  if (areTokensStillValid()) {
    console.log('[setup] Existing JWT tokens are still valid — skipping regeneration.');
    return;
  }

  console.log('[setup] Existing JWT tokens expired or near expiry — regenerating...');

  const privateKeyPem = readFileSync(KEY_PATH, 'utf8');

  function signToken(payload: Record<string, unknown>): string {
    return jwt.sign(payload, privateKeyPem, {
      algorithm: 'RS256',
      expiresIn: '24h',
    });
  }

  const ownerToken = signToken({
    sub: 'user-123',
    user_id: 'user-123',
    tenant_id: '',
    organization_id: 'org-001',
    roles: ['Owner'],
  });

  const viewerToken = signToken({
    sub: 'viewer-user',
    user_id: 'viewer-user',
    tenant_id: '',
    organization_id: 'org-001',
    roles: ['Viewer'],
  });

  const editorToken = signToken({
    sub: 'editor-user',
    user_id: 'editor-user',
    tenant_id: '',
    organization_id: 'org-001',
    roles: ['Editor'],
  });

  const generatedAt = new Date().toISOString();

  const content = [
    '// @ctx: M2.1/M2.5 E2E test JWT tokens — AUTO-GENERATED by global-setup.ts.',
    '// DO NOT EDIT manually — tokens are regenerated before test runs when needed.',
    '// Signed with test-jwt-key.pem (RS256). Verified by JWT_DEV_PUBLIC_KEY_PEM in',
    '// deploy/docker-compose.test.yml.',
    `// Generated: ${generatedAt} (expires in 24h)`,
    '',
    `export const OWNER_JWT = '${ownerToken}';`,
    '',
    `export const VIEWER_JWT = '${viewerToken}';`,
    '',
    `export const EDITOR_JWT = '${editorToken}';`,
    '',
  ].join('\n');

  writeFileSync(OUTPUT_PATH, content, 'utf8');
  console.log(`[setup] Fresh JWT tokens written → ${OUTPUT_PATH}`);
}

export default setup;
