name: vedo-core-docs

services:
  docs-user:
    image: nginx:1.25-alpine
    restart: unless-stopped
    profiles: ["documentation"]
    volumes:
      - ./docs/antora/build/site/user-guide:/usr/share/nginx/html:ro
    ports: ["5000:5000"]
    command: ["sh", "-c", "sed -i 's/listen       80;/listen       5000;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

  docs-dev:
    image: nginx:1.25-alpine
    restart: unless-stopped
    profiles: ["documentation"]
    volumes:
      - ./docs/antora/build/site/developer-guide:/usr/share/nginx/html:ro
    ports: ["5001:5001"]
    command: ["sh", "-c", "sed -i 's/listen       80;/listen       5001;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

  docs-admin:
    image: nginx:1.25-alpine
    restart: unless-stopped
    profiles: ["documentation"]
    volumes:
      - ./docs/antora/build/site/admin-guide:/usr/share/nginx/html:ro
    ports: ["5002:5002"]
    command: ["sh", "-c", "sed -i 's/listen       80;/listen       5002;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]

  docs-integrator:
    image: nginx:1.25-alpine
    restart: unless-stopped
    profiles: ["documentation"]
    volumes:
      - ./docs/antora/build/site/integrator-guide:/usr/share/nginx/html:ro
    ports: ["5003:5003"]
    command: ["sh", "-c", "sed -i 's/listen       80;/listen       5003;/' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"]
