// Commenting Service gRPC contract.
// Comments, mentions, and collaboration features.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: commenting/v1/commenting.proto

package commentingv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "vedo-core/src/services/shared/proto/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Comment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OntologyId    string                 `protobuf:"bytes,2,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,3,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"` // IRI of the commented entity (class, property, etc.)
	AuthorId      string                 `protobuf:"bytes,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Body          string                 `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	ParentId      string                 `protobuf:"bytes,6,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"` // reply thread parent
	Mentions      []string               `protobuf:"bytes,7,rep,name=mentions,proto3" json:"mentions,omitempty"`                 // mentioned user IDs
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Comment) Reset() {
	*x = Comment{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Comment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Comment) ProtoMessage() {}

func (x *Comment) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Comment.ProtoReflect.Descriptor instead.
func (*Comment) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{0}
}

func (x *Comment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Comment) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *Comment) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *Comment) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Comment) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *Comment) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Comment) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

func (x *Comment) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Comment) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type CreateCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	ParentId      string                 `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Mentions      []string               `protobuf:"bytes,5,rep,name=mentions,proto3" json:"mentions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentRequest) Reset() {
	*x = CreateCommentRequest{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentRequest) ProtoMessage() {}

func (x *CreateCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentRequest.ProtoReflect.Descriptor instead.
func (*CreateCommentRequest) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCommentRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *CreateCommentRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *CreateCommentRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *CreateCommentRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *CreateCommentRequest) GetMentions() []string {
	if x != nil {
		return x.Mentions
	}
	return nil
}

type CreateCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comment       *Comment               `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommentResponse) Reset() {
	*x = CreateCommentResponse{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommentResponse) ProtoMessage() {}

func (x *CreateCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommentResponse.ProtoReflect.Descriptor instead.
func (*CreateCommentResponse) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommentResponse) GetComment() *Comment {
	if x != nil {
		return x.Comment
	}
	return nil
}

func (x *CreateCommentResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListCommentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	EntityId      string                 `protobuf:"bytes,2,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,3,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsRequest) Reset() {
	*x = ListCommentsRequest{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsRequest) ProtoMessage() {}

func (x *ListCommentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsRequest.ProtoReflect.Descriptor instead.
func (*ListCommentsRequest) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{3}
}

func (x *ListCommentsRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *ListCommentsRequest) GetEntityId() string {
	if x != nil {
		return x.EntityId
	}
	return ""
}

func (x *ListCommentsRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListCommentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Comments      []*Comment             `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommentsResponse) Reset() {
	*x = ListCommentsResponse{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommentsResponse) ProtoMessage() {}

func (x *ListCommentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommentsResponse.ProtoReflect.Descriptor instead.
func (*ListCommentsResponse) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{4}
}

func (x *ListCommentsResponse) GetComments() []*Comment {
	if x != nil {
		return x.Comments
	}
	return nil
}

func (x *ListCommentsResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListCommentsResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteCommentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommentId     string                 `protobuf:"bytes,1,opt,name=comment_id,json=commentId,proto3" json:"comment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentRequest) Reset() {
	*x = DeleteCommentRequest{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentRequest) ProtoMessage() {}

func (x *DeleteCommentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentRequest.ProtoReflect.Descriptor instead.
func (*DeleteCommentRequest) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCommentRequest) GetCommentId() string {
	if x != nil {
		return x.CommentId
	}
	return ""
}

type DeleteCommentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCommentResponse) Reset() {
	*x = DeleteCommentResponse{}
	mi := &file_commenting_v1_commenting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCommentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCommentResponse) ProtoMessage() {}

func (x *DeleteCommentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commenting_v1_commenting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCommentResponse.ProtoReflect.Descriptor instead.
func (*DeleteCommentResponse) Descriptor() ([]byte, []int) {
	return file_commenting_v1_commenting_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteCommentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCommentResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_commenting_v1_commenting_proto protoreflect.FileDescriptor

const file_commenting_v1_commenting_proto_rawDesc = "" +
	"\n" +
	"\x1ecommenting/v1/commenting.proto\x12\x12vedo.commenting.v1\x1a\x16common/v1/common.proto\"\xff\x01\n" +
	"\aComment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vontology_id\x18\x02 \x01(\tR\n" +
	"ontologyId\x12\x1b\n" +
	"\tentity_id\x18\x03 \x01(\tR\bentityId\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04body\x18\x05 \x01(\tR\x04body\x12\x1b\n" +
	"\tparent_id\x18\x06 \x01(\tR\bparentId\x12\x1a\n" +
	"\bmentions\x18\a \x03(\tR\bmentions\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\"\xa1\x01\n" +
	"\x14CreateCommentRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x12\x1a\n" +
	"\bmentions\x18\x05 \x03(\tR\bmentions\"\x81\x01\n" +
	"\x15CreateCommentResponse\x125\n" +
	"\acomment\x18\x01 \x01(\v2\x1b.vedo.commenting.v1.CommentR\acomment\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"\x96\x01\n" +
	"\x13ListCommentsRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1b\n" +
	"\tentity_id\x18\x02 \x01(\tR\bentityId\x12A\n" +
	"\n" +
	"pagination\x18\x03 \x01(\v2!.vedo.common.v1.PaginationRequestR\n" +
	"pagination\"\xc6\x01\n" +
	"\x14ListCommentsResponse\x127\n" +
	"\bcomments\x18\x01 \x03(\v2\x1b.vedo.commenting.v1.CommentR\bcomments\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".vedo.common.v1.PaginationResponseR\n" +
	"pagination\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"5\n" +
	"\x14DeleteCommentRequest\x12\x1d\n" +
	"\n" +
	"comment_id\x18\x01 \x01(\tR\tcommentId\"d\n" +
	"\x15DeleteCommentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error2\xc2\x02\n" +
	"\x11CommentingService\x12d\n" +
	"\rCreateComment\x12(.vedo.commenting.v1.CreateCommentRequest\x1a).vedo.commenting.v1.CreateCommentResponse\x12a\n" +
	"\fListComments\x12'.vedo.commenting.v1.ListCommentsRequest\x1a(.vedo.commenting.v1.ListCommentsResponse\x12d\n" +
	"\rDeleteComment\x12(.vedo.commenting.v1.DeleteCommentRequest\x1a).vedo.commenting.v1.DeleteCommentResponseBZ\n" +
	"\x16com.vedo.commenting.v1P\x01Z>vedo-core/src/services/shared/proto/commenting/v1;commentingv1b\x06proto3"

var (
	file_commenting_v1_commenting_proto_rawDescOnce sync.Once
	file_commenting_v1_commenting_proto_rawDescData []byte
)

func file_commenting_v1_commenting_proto_rawDescGZIP() []byte {
	file_commenting_v1_commenting_proto_rawDescOnce.Do(func() {
		file_commenting_v1_commenting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_commenting_v1_commenting_proto_rawDesc), len(file_commenting_v1_commenting_proto_rawDesc)))
	})
	return file_commenting_v1_commenting_proto_rawDescData
}

var file_commenting_v1_commenting_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_commenting_v1_commenting_proto_goTypes = []any{
	(*Comment)(nil),               // 0: vedo.commenting.v1.Comment
	(*CreateCommentRequest)(nil),  // 1: vedo.commenting.v1.CreateCommentRequest
	(*CreateCommentResponse)(nil), // 2: vedo.commenting.v1.CreateCommentResponse
	(*ListCommentsRequest)(nil),   // 3: vedo.commenting.v1.ListCommentsRequest
	(*ListCommentsResponse)(nil),  // 4: vedo.commenting.v1.ListCommentsResponse
	(*DeleteCommentRequest)(nil),  // 5: vedo.commenting.v1.DeleteCommentRequest
	(*DeleteCommentResponse)(nil), // 6: vedo.commenting.v1.DeleteCommentResponse
	(*v1.ErrorDetail)(nil),        // 7: vedo.common.v1.ErrorDetail
	(*v1.PaginationRequest)(nil),  // 8: vedo.common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil), // 9: vedo.common.v1.PaginationResponse
}
var file_commenting_v1_commenting_proto_depIdxs = []int32{
	0,  // 0: vedo.commenting.v1.CreateCommentResponse.comment:type_name -> vedo.commenting.v1.Comment
	7,  // 1: vedo.commenting.v1.CreateCommentResponse.error:type_name -> vedo.common.v1.ErrorDetail
	8,  // 2: vedo.commenting.v1.ListCommentsRequest.pagination:type_name -> vedo.common.v1.PaginationRequest
	0,  // 3: vedo.commenting.v1.ListCommentsResponse.comments:type_name -> vedo.commenting.v1.Comment
	9,  // 4: vedo.commenting.v1.ListCommentsResponse.pagination:type_name -> vedo.common.v1.PaginationResponse
	7,  // 5: vedo.commenting.v1.ListCommentsResponse.error:type_name -> vedo.common.v1.ErrorDetail
	7,  // 6: vedo.commenting.v1.DeleteCommentResponse.error:type_name -> vedo.common.v1.ErrorDetail
	1,  // 7: vedo.commenting.v1.CommentingService.CreateComment:input_type -> vedo.commenting.v1.CreateCommentRequest
	3,  // 8: vedo.commenting.v1.CommentingService.ListComments:input_type -> vedo.commenting.v1.ListCommentsRequest
	5,  // 9: vedo.commenting.v1.CommentingService.DeleteComment:input_type -> vedo.commenting.v1.DeleteCommentRequest
	2,  // 10: vedo.commenting.v1.CommentingService.CreateComment:output_type -> vedo.commenting.v1.CreateCommentResponse
	4,  // 11: vedo.commenting.v1.CommentingService.ListComments:output_type -> vedo.commenting.v1.ListCommentsResponse
	6,  // 12: vedo.commenting.v1.CommentingService.DeleteComment:output_type -> vedo.commenting.v1.DeleteCommentResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_commenting_v1_commenting_proto_init() }
func file_commenting_v1_commenting_proto_init() {
	if File_commenting_v1_commenting_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commenting_v1_commenting_proto_rawDesc), len(file_commenting_v1_commenting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commenting_v1_commenting_proto_goTypes,
		DependencyIndexes: file_commenting_v1_commenting_proto_depIdxs,
		MessageInfos:      file_commenting_v1_commenting_proto_msgTypes,
	}.Build()
	File_commenting_v1_commenting_proto = out.File
	file_commenting_v1_commenting_proto_goTypes = nil
	file_commenting_v1_commenting_proto_depIdxs = nil
}
