#!/bin/sh
# =============================================================================
# docker-entrypoint.sh — Generates runtime config for VEDO frontend.
# =============================================================================
# SECURITY BOUNDARY — config.js is served publicly by nginx at /config.js.
# Only NON-SENSITIVE values are exposed here:
#   - Keycloak public URL, realm, client_id (public OIDC metadata)
#   - GraphQL endpoint path
#   - Feature flags (SKIP_AUTH, USE_MOCK_API)
#   - App version and environment name
#
# NEVER add secrets (passwords, API keys, tokens, client secrets) to this
# heredoc — they would be served to any client that requests /config.js.
#
# All values come from VEDO_* environment variables set in docker-compose.
# =============================================================================

CONFIG_FILE=/usr/share/nginx/html/config.js

# ═══════════════════════════════════════════════════════════════════════════
# Security gate: SKIP_AUTH must be "false" in production.
# Prevents accidentally deploying auth-bypass to production containers.
# ═══════════════════════════════════════════════════════════════════════════
if [ "${VEDO_APP_ENV:-dev}" = "production" ] && [ "${VEDO_SKIP_AUTH:-false}" != "false" ]; then
  echo "[entrypoint] FATAL: VEDO_SKIP_AUTH must be 'false' in production (got: '${VEDO_SKIP_AUTH:-false}')" >&2
  exit 1
fi

cat > "$CONFIG_FILE" <<SAFE_EOF
// Auto-generated by docker-entrypoint.sh — DO NOT EDIT.
// Security: this file is served publicly at /config.js.
// It contains ONLY non-sensitive configuration.
window.__VEDO_CONFIG__ = {
  KEYCLOAK_URL: "${VEDO_KEYCLOAK_URL:-http://localhost:8180}",
  KEYCLOAK_REALM: "${VEDO_KEYCLOAK_REALM:-vedo-core}",
  KEYCLOAK_CLIENT_ID: "${VEDO_KEYCLOAK_CLIENT_ID:-vedo-core-frontend}",
  SKIP_AUTH: "${VEDO_SKIP_AUTH:-false}",
  GRAPHQL_ENDPOINT: "${VEDO_GRAPHQL_ENDPOINT:-/api/v1/graphql}",
  USE_MOCK_API: "${VEDO_USE_MOCK_API:-false}",
  APP_VERSION: "${VEDO_APP_VERSION:-dev}",
  APP_ENV: "${VEDO_APP_ENV:-dev}"
};
SAFE_EOF

echo "[entrypoint] config.js generated (public, no secrets)"
exec nginx -g "daemon off;"
