#!/bin/sh
# =============================================================================
# docker-entrypoint.sh — Generates runtime config for VEDO frontend.
# =============================================================================
# SECURITY BOUNDARY — config.js is served publicly by nginx at /config.js.
# ONLY NON-SENSITIVE values are exposed here:
#   - Keycloak public URL, realm, client_id (public OIDC metadata)
#   - GraphQL endpoint path
#   - Feature flags (SKIP_AUTH, USE_MOCK_API)
#   - App version and environment name
#
# DEV-ONLY EXCEPTION — DEV_JWT_TOKEN:
#   The dev Makefile (`make docker-up` with ENV=dev) mints a fresh self-signed
#   RS256 JWT on the HOST (node + jsonwebtoken + tests/e2e/scripts/test-jwt-key.pem)
#   and passes it as VEDO_DEV_JWT_TOKEN. The entrypoint copies it into config.js.
#   The token is only accepted by the dev API Gateway (JWT_DEV_PUBLIC_KEY_PEM
#   active) and is NEVER present in production builds — the security gate below
#   refuses to boot with VEDO_SKIP_AUTH enabled in a production environment,
#   and the production Makefile flow does not set VEDO_DEV_JWT_TOKEN.
#
# NEVER add secrets (passwords, API keys, client secrets) to this heredoc —
# they would be served to any client that requests /config.js.
#
# All values come from VEDO_* environment variables set in docker-compose.
# =============================================================================

CONFIG_FILE=/usr/share/nginx/html/config.js

# ═══════════════════════════════════════════════════════════════════════════
# Security gate: SKIP_AUTH must be "false" in production.
# Prevents accidentally deploying auth-bypass to production containers.
# ═══════════════════════════════════════════════════════════════════════════
if [ "${VEDO_APP_ENV:-dev}" = "production" ] && [ "${VEDO_SKIP_AUTH:-false}" != "false" ]; then
  echo "[entrypoint] FATAL: VEDO_SKIP_AUTH must be 'false' in production (got: '${VEDO_SKIP_AUTH:-false}')" >&2
  exit 1
fi

# ═══════════════════════════════════════════════════════════════════════════
# Dev JWT bootstrap (VEDO_DEV_JWT_TOKEN) — injected by the dev Makefile at
# `make docker-up` time (host-side minting, see deploy/dev-jwt/gen-dev-jwt.js).
# Only honored when SKIP_AUTH is enabled (dev/test images) so it can never
# leak into a production bundle.
# ═══════════════════════════════════════════════════════════════════════════
DEV_JWT_TOKEN=""
if [ "${VEDO_SKIP_AUTH:-false}" = "true" ] && [ -n "${VEDO_DEV_JWT_TOKEN:-}" ]; then
  DEV_JWT_TOKEN="${VEDO_DEV_JWT_TOKEN}"
  echo "[entrypoint] dev JWT loaded from VEDO_DEV_JWT_TOKEN (roles=Owner, exp=24h)"
fi

cat > "$CONFIG_FILE" <<SAFE_EOF
// Auto-generated by docker-entrypoint.sh — DO NOT EDIT.
// Security: this file is served publicly at /config.js.
// It contains ONLY non-sensitive configuration (dev JWT is self-signed and
// only accepted by the dev API Gateway).
window.__VEDO_CONFIG__ = {
  KEYCLOAK_URL: "${VEDO_KEYCLOAK_URL:-http://localhost:8180}",
  KEYCLOAK_REALM: "${VEDO_KEYCLOAK_REALM:-vedo-core}",
  KEYCLOAK_CLIENT_ID: "${VEDO_KEYCLOAK_CLIENT_ID:-vedo-core-frontend}",
  SKIP_AUTH: "${VEDO_SKIP_AUTH:-false}",
  GRAPHQL_ENDPOINT: "${VEDO_GRAPHQL_ENDPOINT:-/api/v1/graphql}",
  USE_MOCK_API: "${VEDO_USE_MOCK_API:-false}",
  APP_VERSION: "${VEDO_APP_VERSION:-dev}",
  APP_ENV: "${VEDO_APP_ENV:-dev}",
  DEV_JWT_TOKEN: "${DEV_JWT_TOKEN}"
};
SAFE_EOF

# Remove the pre-compressed config.js.gz baked at build time (it still holds
# the public/config.js placeholder). With gzip_static on, nginx would serve
# that stale .gz to gzip-capable clients (browsers) instead of the fresh
# config.js generated above — leaving window.__VEDO_CONFIG__ as the
# placeholder (no SKIP_AUTH) and breaking dev auth bypass. The regular
# "gzip on" directive re-compresses the fresh file on the fly.
rm -f "${CONFIG_FILE}.gz"

echo "[entrypoint] config.js generated (public, no secrets)"
exec nginx -g "daemon off;"
