overrides:
  brace-expansion: ^5.0.8
  postcss: ^8.5.18

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - lefthook
  - vue-demi

allowBuilds:
  '@biomejs/biome': true
  esbuild: true
  lefthook: true
  vue-demi: true
