// Publisher Service gRPC contract.
// Ontology snapshot publishing and retrieval.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: publisher/v1/publisher.proto

package publisherv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PublisherService_PublishSnapshot_FullMethodName   = "/vedo.publisher.v1.PublisherService/PublishSnapshot"
	PublisherService_GetPublished_FullMethodName      = "/vedo.publisher.v1.PublisherService/GetPublished"
	PublisherService_ListPublished_FullMethodName     = "/vedo.publisher.v1.PublisherService/ListPublished"
	PublisherService_UnpublishSnapshot_FullMethodName = "/vedo.publisher.v1.PublisherService/UnpublishSnapshot"
)

// PublisherServiceClient is the client API for PublisherService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PublisherServiceClient interface {
	PublishSnapshot(ctx context.Context, in *PublishSnapshotRequest, opts ...grpc.CallOption) (*PublishSnapshotResponse, error)
	GetPublished(ctx context.Context, in *GetPublishedRequest, opts ...grpc.CallOption) (*GetPublishedResponse, error)
	ListPublished(ctx context.Context, in *ListPublishedRequest, opts ...grpc.CallOption) (*ListPublishedResponse, error)
	UnpublishSnapshot(ctx context.Context, in *UnpublishSnapshotRequest, opts ...grpc.CallOption) (*UnpublishSnapshotResponse, error)
}

type publisherServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPublisherServiceClient(cc grpc.ClientConnInterface) PublisherServiceClient {
	return &publisherServiceClient{cc}
}

func (c *publisherServiceClient) PublishSnapshot(ctx context.Context, in *PublishSnapshotRequest, opts ...grpc.CallOption) (*PublishSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishSnapshotResponse)
	err := c.cc.Invoke(ctx, PublisherService_PublishSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) GetPublished(ctx context.Context, in *GetPublishedRequest, opts ...grpc.CallOption) (*GetPublishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublishedResponse)
	err := c.cc.Invoke(ctx, PublisherService_GetPublished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) ListPublished(ctx context.Context, in *ListPublishedRequest, opts ...grpc.CallOption) (*ListPublishedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublishedResponse)
	err := c.cc.Invoke(ctx, PublisherService_ListPublished_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherServiceClient) UnpublishSnapshot(ctx context.Context, in *UnpublishSnapshotRequest, opts ...grpc.CallOption) (*UnpublishSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnpublishSnapshotResponse)
	err := c.cc.Invoke(ctx, PublisherService_UnpublishSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherServiceServer is the server API for PublisherService service.
// All implementations must embed UnimplementedPublisherServiceServer
// for forward compatibility.
type PublisherServiceServer interface {
	PublishSnapshot(context.Context, *PublishSnapshotRequest) (*PublishSnapshotResponse, error)
	GetPublished(context.Context, *GetPublishedRequest) (*GetPublishedResponse, error)
	ListPublished(context.Context, *ListPublishedRequest) (*ListPublishedResponse, error)
	UnpublishSnapshot(context.Context, *UnpublishSnapshotRequest) (*UnpublishSnapshotResponse, error)
	mustEmbedUnimplementedPublisherServiceServer()
}

// UnimplementedPublisherServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPublisherServiceServer struct{}

func (UnimplementedPublisherServiceServer) PublishSnapshot(context.Context, *PublishSnapshotRequest) (*PublishSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PublishSnapshot not implemented")
}
func (UnimplementedPublisherServiceServer) GetPublished(context.Context, *GetPublishedRequest) (*GetPublishedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPublished not implemented")
}
func (UnimplementedPublisherServiceServer) ListPublished(context.Context, *ListPublishedRequest) (*ListPublishedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPublished not implemented")
}
func (UnimplementedPublisherServiceServer) UnpublishSnapshot(context.Context, *UnpublishSnapshotRequest) (*UnpublishSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnpublishSnapshot not implemented")
}
func (UnimplementedPublisherServiceServer) mustEmbedUnimplementedPublisherServiceServer() {}
func (UnimplementedPublisherServiceServer) testEmbeddedByValue()                          {}

// UnsafePublisherServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PublisherServiceServer will
// result in compilation errors.
type UnsafePublisherServiceServer interface {
	mustEmbedUnimplementedPublisherServiceServer()
}

func RegisterPublisherServiceServer(s grpc.ServiceRegistrar, srv PublisherServiceServer) {
	// If the following call panics, it indicates UnimplementedPublisherServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PublisherService_ServiceDesc, srv)
}

func _PublisherService_PublishSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).PublishSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublisherService_PublishSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).PublishSnapshot(ctx, req.(*PublishSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_GetPublished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).GetPublished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublisherService_GetPublished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).GetPublished(ctx, req.(*GetPublishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_ListPublished_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublishedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).ListPublished(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublisherService_ListPublished_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).ListPublished(ctx, req.(*ListPublishedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PublisherService_UnpublishSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServiceServer).UnpublishSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PublisherService_UnpublishSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServiceServer).UnpublishSnapshot(ctx, req.(*UnpublishSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PublisherService_ServiceDesc is the grpc.ServiceDesc for PublisherService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PublisherService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vedo.publisher.v1.PublisherService",
	HandlerType: (*PublisherServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PublishSnapshot",
			Handler:    _PublisherService_PublishSnapshot_Handler,
		},
		{
			MethodName: "GetPublished",
			Handler:    _PublisherService_GetPublished_Handler,
		},
		{
			MethodName: "ListPublished",
			Handler:    _PublisherService_ListPublished_Handler,
		},
		{
			MethodName: "UnpublishSnapshot",
			Handler:    _PublisherService_UnpublishSnapshot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "publisher/v1/publisher.proto",
}
