// Publisher Service gRPC contract.
// Ontology snapshot publishing and retrieval.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: publisher/v1/publisher.proto

package publisherv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
	v1 "vedo-core/src/services/shared/proto/common/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublishedSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OntologyId    string                 `protobuf:"bytes,2,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	VersionTag    string                 `protobuf:"bytes,3,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"` // e.g., "v1.0.0"
	CommitId      string                 `protobuf:"bytes,4,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`       // source commit hash
	Doi           string                 `protobuf:"bytes,5,opt,name=doi,proto3" json:"doi,omitempty"`                                 // optional DOI
	IsLatest      bool                   `protobuf:"varint,6,opt,name=is_latest,json=isLatest,proto3" json:"is_latest,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	PublishedBy   string                 `protobuf:"bytes,8,opt,name=published_by,json=publishedBy,proto3" json:"published_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishedSnapshot) Reset() {
	*x = PublishedSnapshot{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishedSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishedSnapshot) ProtoMessage() {}

func (x *PublishedSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishedSnapshot.ProtoReflect.Descriptor instead.
func (*PublishedSnapshot) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{0}
}

func (x *PublishedSnapshot) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PublishedSnapshot) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *PublishedSnapshot) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *PublishedSnapshot) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *PublishedSnapshot) GetDoi() string {
	if x != nil {
		return x.Doi
	}
	return ""
}

func (x *PublishedSnapshot) GetIsLatest() bool {
	if x != nil {
		return x.IsLatest
	}
	return false
}

func (x *PublishedSnapshot) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *PublishedSnapshot) GetPublishedBy() string {
	if x != nil {
		return x.PublishedBy
	}
	return ""
}

type PublishSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	CommitId      string                 `protobuf:"bytes,2,opt,name=commit_id,json=commitId,proto3" json:"commit_id,omitempty"`
	VersionTag    string                 `protobuf:"bytes,3,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"`
	PublishedBy   string                 `protobuf:"bytes,4,opt,name=published_by,json=publishedBy,proto3" json:"published_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSnapshotRequest) Reset() {
	*x = PublishSnapshotRequest{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSnapshotRequest) ProtoMessage() {}

func (x *PublishSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSnapshotRequest.ProtoReflect.Descriptor instead.
func (*PublishSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{1}
}

func (x *PublishSnapshotRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *PublishSnapshotRequest) GetCommitId() string {
	if x != nil {
		return x.CommitId
	}
	return ""
}

func (x *PublishSnapshotRequest) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

func (x *PublishSnapshotRequest) GetPublishedBy() string {
	if x != nil {
		return x.PublishedBy
	}
	return ""
}

type PublishSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *PublishedSnapshot     `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishSnapshotResponse) Reset() {
	*x = PublishSnapshotResponse{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishSnapshotResponse) ProtoMessage() {}

func (x *PublishSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishSnapshotResponse.ProtoReflect.Descriptor instead.
func (*PublishSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{2}
}

func (x *PublishSnapshotResponse) GetSnapshot() *PublishedSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *PublishSnapshotResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetPublishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	VersionTag    string                 `protobuf:"bytes,2,opt,name=version_tag,json=versionTag,proto3" json:"version_tag,omitempty"` // empty = latest
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedRequest) Reset() {
	*x = GetPublishedRequest{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedRequest) ProtoMessage() {}

func (x *GetPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedRequest.ProtoReflect.Descriptor instead.
func (*GetPublishedRequest) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{3}
}

func (x *GetPublishedRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *GetPublishedRequest) GetVersionTag() string {
	if x != nil {
		return x.VersionTag
	}
	return ""
}

type GetPublishedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *PublishedSnapshot     `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	OntologyTtl   string                 `protobuf:"bytes,2,opt,name=ontology_ttl,json=ontologyTtl,proto3" json:"ontology_ttl,omitempty"` // Turtle serialization of the ontology at this snapshot
	Error         *v1.ErrorDetail        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublishedResponse) Reset() {
	*x = GetPublishedResponse{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublishedResponse) ProtoMessage() {}

func (x *GetPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublishedResponse.ProtoReflect.Descriptor instead.
func (*GetPublishedResponse) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{4}
}

func (x *GetPublishedResponse) GetSnapshot() *PublishedSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *GetPublishedResponse) GetOntologyTtl() string {
	if x != nil {
		return x.OntologyTtl
	}
	return ""
}

func (x *GetPublishedResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type ListPublishedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	Pagination    *v1.PaginationRequest  `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishedRequest) Reset() {
	*x = ListPublishedRequest{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishedRequest) ProtoMessage() {}

func (x *ListPublishedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishedRequest.ProtoReflect.Descriptor instead.
func (*ListPublishedRequest) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{5}
}

func (x *ListPublishedRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *ListPublishedRequest) GetPagination() *v1.PaginationRequest {
	if x != nil {
		return x.Pagination
	}
	return nil
}

type ListPublishedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshots     []*PublishedSnapshot   `protobuf:"bytes,1,rep,name=snapshots,proto3" json:"snapshots,omitempty"`
	Pagination    *v1.PaginationResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPublishedResponse) Reset() {
	*x = ListPublishedResponse{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPublishedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPublishedResponse) ProtoMessage() {}

func (x *ListPublishedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPublishedResponse.ProtoReflect.Descriptor instead.
func (*ListPublishedResponse) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{6}
}

func (x *ListPublishedResponse) GetSnapshots() []*PublishedSnapshot {
	if x != nil {
		return x.Snapshots
	}
	return nil
}

func (x *ListPublishedResponse) GetPagination() *v1.PaginationResponse {
	if x != nil {
		return x.Pagination
	}
	return nil
}

func (x *ListPublishedResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

type UnpublishSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OntologyId    string                 `protobuf:"bytes,1,opt,name=ontology_id,json=ontologyId,proto3" json:"ontology_id,omitempty"`
	SnapshotId    string                 `protobuf:"bytes,2,opt,name=snapshot_id,json=snapshotId,proto3" json:"snapshot_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishSnapshotRequest) Reset() {
	*x = UnpublishSnapshotRequest{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishSnapshotRequest) ProtoMessage() {}

func (x *UnpublishSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishSnapshotRequest.ProtoReflect.Descriptor instead.
func (*UnpublishSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{7}
}

func (x *UnpublishSnapshotRequest) GetOntologyId() string {
	if x != nil {
		return x.OntologyId
	}
	return ""
}

func (x *UnpublishSnapshotRequest) GetSnapshotId() string {
	if x != nil {
		return x.SnapshotId
	}
	return ""
}

type UnpublishSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *v1.ErrorDetail        `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnpublishSnapshotResponse) Reset() {
	*x = UnpublishSnapshotResponse{}
	mi := &file_publisher_v1_publisher_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnpublishSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnpublishSnapshotResponse) ProtoMessage() {}

func (x *UnpublishSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_publisher_v1_publisher_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnpublishSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UnpublishSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_publisher_v1_publisher_proto_rawDescGZIP(), []int{8}
}

func (x *UnpublishSnapshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UnpublishSnapshotResponse) GetError() *v1.ErrorDetail {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_publisher_v1_publisher_proto protoreflect.FileDescriptor

const file_publisher_v1_publisher_proto_rawDesc = "" +
	"\n" +
	"\x1cpublisher/v1/publisher.proto\x12\x11vedo.publisher.v1\x1a\x16common/v1/common.proto\"\xf3\x01\n" +
	"\x11PublishedSnapshot\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vontology_id\x18\x02 \x01(\tR\n" +
	"ontologyId\x12\x1f\n" +
	"\vversion_tag\x18\x03 \x01(\tR\n" +
	"versionTag\x12\x1b\n" +
	"\tcommit_id\x18\x04 \x01(\tR\bcommitId\x12\x10\n" +
	"\x03doi\x18\x05 \x01(\tR\x03doi\x12\x1b\n" +
	"\tis_latest\x18\x06 \x01(\bR\bisLatest\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\x12!\n" +
	"\fpublished_by\x18\b \x01(\tR\vpublishedBy\"\x9a\x01\n" +
	"\x16PublishSnapshotRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1b\n" +
	"\tcommit_id\x18\x02 \x01(\tR\bcommitId\x12\x1f\n" +
	"\vversion_tag\x18\x03 \x01(\tR\n" +
	"versionTag\x12!\n" +
	"\fpublished_by\x18\x04 \x01(\tR\vpublishedBy\"\x8e\x01\n" +
	"\x17PublishSnapshotResponse\x12@\n" +
	"\bsnapshot\x18\x01 \x01(\v2$.vedo.publisher.v1.PublishedSnapshotR\bsnapshot\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"W\n" +
	"\x13GetPublishedRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1f\n" +
	"\vversion_tag\x18\x02 \x01(\tR\n" +
	"versionTag\"\xae\x01\n" +
	"\x14GetPublishedResponse\x12@\n" +
	"\bsnapshot\x18\x01 \x01(\v2$.vedo.publisher.v1.PublishedSnapshotR\bsnapshot\x12!\n" +
	"\fontology_ttl\x18\x02 \x01(\tR\vontologyTtl\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"z\n" +
	"\x14ListPublishedRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12A\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2!.vedo.common.v1.PaginationRequestR\n" +
	"pagination\"\xd2\x01\n" +
	"\x15ListPublishedResponse\x12B\n" +
	"\tsnapshots\x18\x01 \x03(\v2$.vedo.publisher.v1.PublishedSnapshotR\tsnapshots\x12B\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\".vedo.common.v1.PaginationResponseR\n" +
	"pagination\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error\"\\\n" +
	"\x18UnpublishSnapshotRequest\x12\x1f\n" +
	"\vontology_id\x18\x01 \x01(\tR\n" +
	"ontologyId\x12\x1f\n" +
	"\vsnapshot_id\x18\x02 \x01(\tR\n" +
	"snapshotId\"h\n" +
	"\x19UnpublishSnapshotResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x121\n" +
	"\x05error\x18\x02 \x01(\v2\x1b.vedo.common.v1.ErrorDetailR\x05error2\xb1\x03\n" +
	"\x10PublisherService\x12h\n" +
	"\x0fPublishSnapshot\x12).vedo.publisher.v1.PublishSnapshotRequest\x1a*.vedo.publisher.v1.PublishSnapshotResponse\x12_\n" +
	"\fGetPublished\x12&.vedo.publisher.v1.GetPublishedRequest\x1a'.vedo.publisher.v1.GetPublishedResponse\x12b\n" +
	"\rListPublished\x12'.vedo.publisher.v1.ListPublishedRequest\x1a(.vedo.publisher.v1.ListPublishedResponse\x12n\n" +
	"\x11UnpublishSnapshot\x12+.vedo.publisher.v1.UnpublishSnapshotRequest\x1a,.vedo.publisher.v1.UnpublishSnapshotResponseBW\n" +
	"\x15com.vedo.publisher.v1P\x01Z<vedo-core/src/services/shared/proto/publisher/v1;publisherv1b\x06proto3"

var (
	file_publisher_v1_publisher_proto_rawDescOnce sync.Once
	file_publisher_v1_publisher_proto_rawDescData []byte
)

func file_publisher_v1_publisher_proto_rawDescGZIP() []byte {
	file_publisher_v1_publisher_proto_rawDescOnce.Do(func() {
		file_publisher_v1_publisher_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_publisher_v1_publisher_proto_rawDesc), len(file_publisher_v1_publisher_proto_rawDesc)))
	})
	return file_publisher_v1_publisher_proto_rawDescData
}

var file_publisher_v1_publisher_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_publisher_v1_publisher_proto_goTypes = []any{
	(*PublishedSnapshot)(nil),         // 0: vedo.publisher.v1.PublishedSnapshot
	(*PublishSnapshotRequest)(nil),    // 1: vedo.publisher.v1.PublishSnapshotRequest
	(*PublishSnapshotResponse)(nil),   // 2: vedo.publisher.v1.PublishSnapshotResponse
	(*GetPublishedRequest)(nil),       // 3: vedo.publisher.v1.GetPublishedRequest
	(*GetPublishedResponse)(nil),      // 4: vedo.publisher.v1.GetPublishedResponse
	(*ListPublishedRequest)(nil),      // 5: vedo.publisher.v1.ListPublishedRequest
	(*ListPublishedResponse)(nil),     // 6: vedo.publisher.v1.ListPublishedResponse
	(*UnpublishSnapshotRequest)(nil),  // 7: vedo.publisher.v1.UnpublishSnapshotRequest
	(*UnpublishSnapshotResponse)(nil), // 8: vedo.publisher.v1.UnpublishSnapshotResponse
	(*v1.ErrorDetail)(nil),            // 9: vedo.common.v1.ErrorDetail
	(*v1.PaginationRequest)(nil),      // 10: vedo.common.v1.PaginationRequest
	(*v1.PaginationResponse)(nil),     // 11: vedo.common.v1.PaginationResponse
}
var file_publisher_v1_publisher_proto_depIdxs = []int32{
	0,  // 0: vedo.publisher.v1.PublishSnapshotResponse.snapshot:type_name -> vedo.publisher.v1.PublishedSnapshot
	9,  // 1: vedo.publisher.v1.PublishSnapshotResponse.error:type_name -> vedo.common.v1.ErrorDetail
	0,  // 2: vedo.publisher.v1.GetPublishedResponse.snapshot:type_name -> vedo.publisher.v1.PublishedSnapshot
	9,  // 3: vedo.publisher.v1.GetPublishedResponse.error:type_name -> vedo.common.v1.ErrorDetail
	10, // 4: vedo.publisher.v1.ListPublishedRequest.pagination:type_name -> vedo.common.v1.PaginationRequest
	0,  // 5: vedo.publisher.v1.ListPublishedResponse.snapshots:type_name -> vedo.publisher.v1.PublishedSnapshot
	11, // 6: vedo.publisher.v1.ListPublishedResponse.pagination:type_name -> vedo.common.v1.PaginationResponse
	9,  // 7: vedo.publisher.v1.ListPublishedResponse.error:type_name -> vedo.common.v1.ErrorDetail
	9,  // 8: vedo.publisher.v1.UnpublishSnapshotResponse.error:type_name -> vedo.common.v1.ErrorDetail
	1,  // 9: vedo.publisher.v1.PublisherService.PublishSnapshot:input_type -> vedo.publisher.v1.PublishSnapshotRequest
	3,  // 10: vedo.publisher.v1.PublisherService.GetPublished:input_type -> vedo.publisher.v1.GetPublishedRequest
	5,  // 11: vedo.publisher.v1.PublisherService.ListPublished:input_type -> vedo.publisher.v1.ListPublishedRequest
	7,  // 12: vedo.publisher.v1.PublisherService.UnpublishSnapshot:input_type -> vedo.publisher.v1.UnpublishSnapshotRequest
	2,  // 13: vedo.publisher.v1.PublisherService.PublishSnapshot:output_type -> vedo.publisher.v1.PublishSnapshotResponse
	4,  // 14: vedo.publisher.v1.PublisherService.GetPublished:output_type -> vedo.publisher.v1.GetPublishedResponse
	6,  // 15: vedo.publisher.v1.PublisherService.ListPublished:output_type -> vedo.publisher.v1.ListPublishedResponse
	8,  // 16: vedo.publisher.v1.PublisherService.UnpublishSnapshot:output_type -> vedo.publisher.v1.UnpublishSnapshotResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_publisher_v1_publisher_proto_init() }
func file_publisher_v1_publisher_proto_init() {
	if File_publisher_v1_publisher_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_publisher_v1_publisher_proto_rawDesc), len(file_publisher_v1_publisher_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_publisher_v1_publisher_proto_goTypes,
		DependencyIndexes: file_publisher_v1_publisher_proto_depIdxs,
		MessageInfos:      file_publisher_v1_publisher_proto_msgTypes,
	}.Build()
	File_publisher_v1_publisher_proto = out.File
	file_publisher_v1_publisher_proto_goTypes = nil
	file_publisher_v1_publisher_proto_depIdxs = nil
}
