site:
  title: VEDO Core — Руководство пользователя
  url: https://example.com/docs/user
content:
  sources:
    - url: ./
      branches: HEAD
      start_path: docs/antora/user-guide
output:
  dir: ./build/site/user-guide
